### ISSUE TITLE
How to add genomealign tracks

### ISSUE THREAD

**Issue by songtaogui** [lidaof/eg-react#122] opened 2019-07-17 03:49 UTC
Hi,

I have problems loading the genomealign tracks, the browser version I used is V48.4.

I have prepared the genomealign file in the same format of that in the demo site:

Here is the head ten records of my genomealign file: 
[head 10 records of B73_Mo17_axt.gz ](https://github.com/lidaof/eg-react/files/3400026/test_axt.gz)
the file was bgzipped and tabix indexed.

And the configs for the track was like this in `annotationTracks.json` file:
```
"Genome Comparison":[
    {
        "name": "B73_to_Mo17",
        "label": "B73 to Mo17 lastz",
        "querygenome": "Mo17",
        "metadata": {"genome":"B73"},
        "type": "genomealign",
        "mode":"show",
        "url": "/WashU_browser/B73/CompareGenomes/B73_Mo17_axt.gz"
    }
]
```

However, the resulted display shows no erros but nothing in the track: 
![image](https://user-images.githubusercontent.com/14274330/61345650-a17f3d80-a888-11e9-9bd6-ef01f9581e9f.png)

Did I miss something?

Thank you,

SongtaoGui

**Comment by lidaof** [comment] 2019-07-17 05:17
can you try use chr1, chr2 as chromosome names in the file? i see the first line has `1` there
`1	26253	31325	id:0,genomealign:{chr:"chr1",start:40429,stop:45502`? or you just use 1 in the genome file?

**Comment by songtaogui** [comment] 2019-07-17 06:19
Yes, 1 is the chromesome ID in the genome file. I think this may not be the issue, because other tracks (which all use number as chromesome ID ) were correctly displayed.

**Comment by lidaof** [comment] 2019-07-17 14:33
i see. are you running a local version from `npm start` or the build version? I cannot debug this at my side since I don't have your genome. if you are running a local version, can you install React Dev tools and open it to debug. A quick check can be done is to check if this track receives any data from the props. you can get the React dev tools from [here](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) in Chrome.

**Comment by songtaogui** [comment] 2019-07-18 03:07
Hi, sorry that I knew little about React. I have used React Dev tools, and it seems to me that no data received: 

![pic1](https://user-images.githubusercontent.com/14274330/61426128-e324ec80-a94b-11e9-8429-3be47baa8d98.png)


In fact, I have set the browser on a server. Is it OK that you visit the browser [here](http://47.106.251.193:8091/?genome=B73), and navigated to the genomealign track in the `annotation tracks` menu to check it ?

![image](https://user-images.githubusercontent.com/14274330/61425819-bfad7200-a94a-11e9-9edf-1884323fb948.png)

Thank you for your kindly help.

**Comment by lidaof** [comment] 2019-07-18 04:14
Hi @songtaogui , it might be caused by a code update? can you try this, change both querygenome and the genome in metadata to same one?

```
"Genome Comparison":[
    {
        "name": "B73_to_Mo17",
        "label": "B73 to Mo17 lastz",
        "querygenome": "Mo17",
        "metadata": {"genome":"Mo17"},
        "type": "genomealign",
        "mode":"show",
        "url": "/WashU_browser/B73/CompareGenomes/B73_Mo17_axt.gz"
    }
]
```

**Comment by songtaogui** [comment] 2019-07-18 05:54
@lidaof Yes, it works !
Thank you for your help.

**Comment by lidaof** [comment] 2019-07-18 13:56
ok, I am closing this for now. Just let you know the version greater than 48.4 just need the query genome info.

**Closed by lidaof** 2019-07-18 13:56 UTC
