### ISSUE TITLE
Troubling in screenshot with negative value

### ISSUE THREAD

**Issue by hsuh001** [lidaof/eg-react#319] opened 2023-06-06 12:48 UTC
Hi, I was having some problems when screenshotting with a fixed and negative value. Everything was going well in the online browser, as follows:
![image](https://github.com/lidaof/eg-react/assets/55721904/ec8e4f10-8afb-466b-8137-a197fe08db50)
but the tracks were dislocation when I downloaded the screenshot into my personal computer:
![image](https://github.com/lidaof/eg-react/assets/55721904/eec3ddcd-74bf-4343-9f88-0223e8e42447)

Is there a solution to solve this?

Thanks in advance for your help!

**Comment by hsuh001** [comment] 2023-06-06 14:12
> Hi @hsuh001 thanks for using the browser! do you mean the SVG was trimmed on the right side?

No, I mean that in each track, the part of the positive value was at the bottom, and that of the negative value was at the top in the SVG file (or in the second example).

**Comment by hsuh001** [comment] 2023-06-06 14:23
Thank you!

**Comment by lidaof** [comment] 2023-06-18 04:53
Hi @hsuh001 so sorry for late reply. (didn't forget this but was distracted by other things).
I tried some of my bedgraph track files with negative values, I cannot reproduce this error somehow. Would you possible you can send me a session id if your files are hosted remotely? or send a small part of file to me I can troubleshoot. 
Thank you!

**Comment by hsuh001** [comment] 2023-06-18 11:39
Sorry, I'm unable to access GitHub temporally due to the network permission. So I replied to you here using email.
After testing bedgraph track files with negative values, I found that it worked fine if setting "Y-axis scale" to "Auto", but not the value "Fixed". Could this "Fixed" might be the reason?
My bw file is about 300 MB. I will send you if needed soon after.
Thank you!




Jing Xiao
On 6/18/2023 12:54，Daofeng ***@***.***> wrote：

Hi @hsuh001 so sorry for late reply. (didn't forget this but was distracted by other things).
I tried some of my bedgraph track files with negative values, I cannot reproduce this error somehow. Would you possible you can send me a session id if your files are hosted remotely? or send a small part of file to me I can troubleshoot.
Thank you!

**Comment by lidaof** [comment] 2023-06-18 14:52
Hi Jing @hsuh001, reply to email is fine.
I tested with fixed scale, the display is fine, but I indeed found an issue that the axis is gone, but not the problem you showed to me. possible you can send me the first 1000 lines of your file? (you can convert to bedgraph and send me some lines of text with both positive and negative values?) Thank you!

<img width="594" alt="image" src="https://github.com/lidaof/eg-react/assets/102806/5dc7abf2-b417-4915-8816-e7af84f877fd">

**Comment by hsuh001** [comment] 2023-06-19 10:49
Hi, sorry reply now due to some personal affairs. Attachment files are 4 bigwig files, part of raw bigwig fiels (first 1000 lines).
The reference genome is hg38, region range is chr1:1-600000.
It is true that the axis is gone in the download page, but the axis exists in the local file if clicking the download button in both SVG and Pdf format.
The problem might be the fixed value range. If setting as [-1,1] (or [-2, 2] or [-3, 3], and so on), the download file was right. But when the range is asymmetrical, e.g. [-0.5, 1] (or [-1, 2]), the track was wrong. Note the the wrong result was in the download file, so it means that you should click the download button and browse the file in local. After downloading the file using asymmetrical range, when returning to the download web page, the web page get the same wrong result.
Thank you!


Jing Xiao
On 6/18/2023 22:52，Daofeng ***@***.***> wrote：

Hi Jing @hsuh001, reply to email is fine.
I tested with fixed scale, the display is fine, but I indeed found an issue that the axis is gone, but not the problem you showed to me. possible you can send me the first 1000 lines of your file? (you can convert to bedgraph and send me some lines of text with both positive and negative values?) Thank you!

**Comment by lidaof** [comment] 2023-06-23 04:40
Hi @hsuh001 sorry for the delay, please refresh the browser to 54.0.3, this issue (including axis label) should be fixed. Let me know if problem still exists for you. thank you!

**Comment by hsuh001** [comment] 2023-06-23 05:53
Hi, Daofeng, now the result is fine after refreshing the browser. Thank you so much!

**Closed** 2024-04-19 15:18 UTC
