### ISSUE TITLE
Local text track not saved in session?

### ISSUE THREAD

**Issue by gitgitmonkey** [lidaof/eg-react#248] opened 2022-03-01 21:04 UTC
When I upload a local .bed file and save the session, the file disappears when I reload the session.
I saved these coordinates in a local file and uploaded them. Then I created a session with bundle ID e7b291c0-98cd-11ec-9fbb-ef104d3ddc3f

chr7    27153397        27153997
chr7    27154697        27155697

The track isn't available. I don't have this problem with remote tracks.
Is this a bug or a feature? If it's a feature, there are no warnings about sessions not saving local uploaded files, and it's very confusing for users to be able to create a session and then lose all tracks created from local files.
Thanks!

**Comment by lidaof** [comment] 2022-03-01 22:44
Hi @gitgitmonkey, it's not a bug. we documented here: https://eg.readthedocs.io/en/latest/local.html, because browser need ask permission to load local file each time so local files cannot be saved into session.

**Comment by gitgitmonkey** [comment] 2022-03-01 22:54
Thanks for the clarification.
This is a huge limitation of this browser that did not exist in the legacy browser. It makes it prohibitive for people without access to a remote server to easily share sessions. I can't expect PIs to constantly load .json files every time they want to change sessions, besides having to maintain all the files belonging to different projects.
The legacy browser seemed to delete files after a while, which made sessions unreliable, but at least they worked for a while.

**Comment by lidaof** [comment] 2022-03-01 23:08
Hi @gitgitmonkey, yes, you are right. While the design for the current browser is pure client side, there is no backend server for providing file processing service, so we cannot save files as legacy browser did. We provided limited space for track hosting with a random URL if needed (feel free to let me know if you need us to host files). Also we are still maintaining the legacy browser. one way for viewing secure/private data is to run a local browser mirror which could be done pretty easy in Linux/OSX system with nodejs environment.

**Comment by lidaof** [comment] 2022-03-23 16:49
Close this one now. Feel free to open any new issue. Thanks!

**Closed by lidaof** 2022-03-23 16:49 UTC
